-- https://school.programmers.co.kr/learn/courses/30/lessons/131117
-- 5월 식품들의 총매출 조회하기
SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN FOOD_ORDER AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;

-- https://school.programmers.co.kr/learn/courses/30/lessons/131124
-- 그룹별 조건에 맞는 식당 목록 출력하기
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS M
         JOIN REST_REVIEW AS R
              ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) = (
        SELECT COUNT(REVIEW_ID) AS NUM
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY NUM DESC
    LIMIT 1))
ORDER BY REVIEW_DATE, REVIEW_TEXT;

-- https://school.programmers.co.kr/learn/courses/30/lessons/157339
-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
              ON C.CAR_ID = H.CAR_ID
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
              ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
)
  AND DURATION_TYPE = '30일 이상'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
